### PR TITLE
Update the Aruco Library for the newest version.

### PR DESCRIPTION
**Pull request by dbcesar**
This "merge request" updates the Aruco Library for its newest version. The "aruco_create_board.cpp" patch was removed because its changes are already fixed in the newest version of Aruco Library.

### CODE REVIEW

**Comment by doudou** [comment]
@2maz: should the patche(s) be updated ?

**Comment by doudou** [comment]
So, what now ? @dbcesar should update the patch(es) ?

**Comment by 2maz** [comment]
I would say so. @dbcesar can update the patches accordingly, thx!?

**Comment by dbcesar** [comment]
Already done. Sorry for the delay.

**Comment by 2maz** [comment]
Merged after squashing the relevant commits into one.

**Pull request closed without merging**
