### PR TITLE
Bypass graphviz and boost package redefinition warning

### PR DESCRIPTION
**Pull request by g-arjones**
I wish there was a better way to do this... :(

### CODE REVIEW

**Comment by doudou** [comment]
Yeah ... I'm not merging that. I actually prefer the warnings.

The warning appeared after the redefinition, which made fixing it a bit problematic (it would involve removing entries from an existing osdep, which breaks builds). This would have obviously been the best option.

At the autoproj level, we could allow the osdeps entry to tell autoproj that it's fine if there is a redefinition there (e.g. with a '!' marker).

A suggestion at the Rock package set level is to drop the dependency on the orocos.toolchain package set. It's something that will happen anyways, since the orocos.toolchain people are not using autoproj at all. AFAIK, people are using the Rock package sets to bootstrap the orocos toolchain anyways, when they don't want to use ROS.

**Comment by g-arjones** [comment]
> Yeah ... I'm not merging that. I actually prefer the warnings.

That is not suprprising at all... LOL

> A suggestion at the Rock package set level is to drop the dependency on the orocos.toolchain package set

I think that makes the most sense. Anyway, I just wanted the make point (this warnings bother me A LOT)

**Comment by g-arjones** [comment]
I'm closing this.. Let me know if you are willing to accept a PR that copies orocos.osdeps over to rock-package_set.

**Comment by g-arjones** [comment]
great, thanks a lot!

**Pull request closed without merging**
