### PR TITLE
Update external/aruco to build version 3.1.8

### PR DESCRIPTION
**Pull request by pierrewillenbrockdfki**
This updates the sources.yml to reference aruco 3.1.8.

As far as i remember, version 1.2.5 and even 1.3.0 (that is the only not 3.1 version still available for download) fail to compile against a current opencv.

This has been tested with the DFKI internal image_processing/orogen/aruco component. I am not aware of any other users.

@doudou do you want to merge this or rather have me remove external/aruco here and put it into a DFKI internal package_set?

### CODE REVIEW

**Comment by doudou** [comment]
> I would vote for merging, i.e. updating to the latest version, but giving a notification to rock-users.

Then let's do it.

**Comment by 2maz** [comment]
@pierrewillenbrockdfki could you update the source.yml to the recently published version 3.1.11 https://sourceforge.net/projects/aruco/files/3.1.11/aruco-3.1.11.zip/download and then we merge

**Comment by pierrewillenbrockdfki** [comment]
Updated for aruco 3.1.11, then ran the tests of our image_processing/orogen/aruco package. Everything seems fine.
I guess travis-ci only works with branches from this repository, not from external ones.

**Comment by 2maz** [comment]
@pierrewillenbrockdfki thx

**Pull request merged**
