### PR TITLE
update pcl to version 1.8.0

### PR DESCRIPTION
**Pull request by jmachowinski**

### CODE REVIEW

**Comment by doudou** [comment]
This is problematic (not that I am against it but ...). 1.7.x and 1.8.0 are incompatible, and 1.8.0 seem to be not-that-unbuggy. We had to switch back to 1.7.x because we were hitting bugs in 1.8.0.

Maybe wait for 1.8.1 ?

**Comment by jmachowinski** [comment]
There is an annoying bug in 1.7.1 in the ubuntu packages that breaks 
compilation with 16.04 for us. Source build from 1.8 is fine.

**Comment by jmachowinski** [comment]
https://bugs.launchpad.net/ubuntu/+source/pcl/+bug/1573174
https://bugs.launchpad.net/ubuntu/+source/vtk6/+bug/1573234

**Comment by doudou** [comment]
> There is an annoying bug in 1.7.1 in the ubuntu packages that breaks 
compilation with 16.04 for us. Source build from 1.8 is fine.

Funnily enough, we have the exact opposite situation. 1.8 broken, 1.7.1 fine on 16.04

**Comment by chhtz** [comment]
Could we just remove the osdep entry, but keep the tag in source.yml at 1.7.1 for now? This would make it easy to switch to another version on Ubuntu 16.04 with a project-specific overwrite.
Or is there some manual way to overwrite osdeps?

**Comment by chhtz** [comment]
For the record, if someone wants to override this locally, put the following in your overrides.rb:
```
Autoproj.add_osdeps_overrides 'slam/pcl', :force => true
```
and some alternative source/branch/tag inside some overides.d/*.yml

**Pull request closed without merging**
