### PR TITLE
Organize python osdeps in version specific files

### PR DESCRIPTION
**Pull request by 2maz**
Cython definition for python2 will be moved to rock.core package set for consistency reasons

### CODE REVIEW

**Comment by doudou** [comment]
For my information, what are they going to be used for in rock-core ?

**Comment by g-arjones** [comment]
I was wondering whether we could move all the python related stuff to a dedicated package set. As far as I am concerned there's nothing in rock that requires python (and that's a good thing, IMO). 

What do you guys think?

**Comment by 2maz** [comment]
> No wait. They're staying here. Only cython is moving there. Why cython ?

As stated, I moved the definition for consistency reasons since cython is already defined in rock.core in rock.osdeps-python3 (but was not for python2)

**Comment by 2maz** [comment]
> I was wondering whether we could move all the python related stuff to a dedicated package set. As far as I am concerned there's nothing in rock that requires python (and that's a good thing, IMO).

At least optional dependencies exist, e.g., for python bindings.

> What do you guys think?

I am not against it, but would you have this package set then as import in the existing rock package sets or enforce all python dependencies to be optional?

**Comment by g-arjones** [comment]
Not sure how many packages there are and how much work that would be but in principle I think having python dependencies as optional dependencies would be the way to go.

**Comment by planthaber** [comment]
I guess a new package set would be the best

> I am not against it, but would you have this package set then as import in the existing rock package sets or enforce all python dependencies to be optional?

I think so, at least for packages where the bindings are truly optional, others should go into the new python package set.

But I would not auto-import the rock package set, this would allow to use autoproj and the python package set for pure, rock independent, python workspaces.

What about asking if the python package set should be activated as configuration option in rock.core ?

**Comment by 2maz** [comment]
Independently of the extraction into a separate package set, I am still asking for approval to merge this PR, since having the python2 based definition of cython in rock.osdeps is inconsistent and thus breaks some of our builds.

**Comment by doudou** [comment]
> since having the python2 based definition of cython in rock.osdeps is inconsistent and thus breaks some of our builds.

Let's do it then. I wonder why it is in rock-core though.

I personally support having Python support (the selection code that @2maz developed recently, and the osdeps) in the main repositories. It will help anyone that wants to integrate python stuff, and let's face it Python is a popular language.

**Review by doudou — APPROVED** [review]

**Pull request merged**
