### PR TITLE
added constant pose provider component

### PR DESCRIPTION
**Pull request by saarnold**

### CODE REVIEW

**Comment by doudou** [comment]
This is a really bad name given what the component does....

Isn't that a pose integrator ? (I would say a "simple pose integrator" given that it seems to be filter-less)

**Comment by saarnold** [comment]
Constant meaning continuous in time.

**Comment by doudou** [comment]
> Constant meaning continuous in time.

You know that. Noone reading "constant_pose_provider" would know it. Naming, either in code or in packages, is not *for you*, it is for everybody else. I can admit that it is ambiguous at time, but here, not even close.

> Would continuous_pose_provider be any better?

Marginally. IMO the real problem is that you try to describe what the component outputs, not what it does. This is bound to fail as (1) it's very hard in this case and (2) there are many ways to provide the same output. Should all they be called continuous_pose_provider_1, continuous_pose_provider_2, ... ?

Describe the functionality, which IMO here is integrate delta poses (with the nice addition of "correcting" using full poses when they are available)

**Comment by saarnold** [comment]
Fair point. I renamed the component accordingly.

**Comment by doudou** [comment]
:+1:

**Pull request merged**
