### PR TITLE
build an out-of-tree collada plugin for OSG

### PR DESCRIPTION
**Pull request by doudou**

### CODE REVIEW

**Comment by doudou** [comment]
@D-Alex: I've updated the PR, there has been a weird conversion-to-lowercase going on

**Comment by 2maz** [comment]
@D-Alex can you pls check

**Comment by 2maz** [comment]
Bootstraps fine as long as autobuild is most recent version (1.9.3).
I personally would put the "require 'utilrb/pkgconfig'" close to the Utilrb::PkgConfig statement.
Otherwise good to merge.

**Comment by doudou** [comment]
rebased, and moves the `require 'utilrb/pkgconfig'`

**Comment by 2maz** [comment]
Merged

**Pull request merged**
