### PR TITLE
tools/gecode: set configureflags to include building of gist

### PR DESCRIPTION
**Pull request by 2maz**

### CODE REVIEW

**Comment by doudou** [comment]
I'm fine with it. The one thing that gives me pause is that you add Qt as a mandatory dependency, while I would see usage of gecode in embedded systems.

**Comment by 2maz** [comment]
I would be fine with just activating it for amd64 / x86_64 (see update).

I wonder however, whether there is a simpler way to achieve that in autoproj than shown in my current update? Suggestions welcome.
I had a look at [Autoproj.only_on](https://github.com/rock-core/autoproj/blob/8fa1b0c69054e59bec7eeb9ae0ec5d7c52b1a114/lib/autoproj/autobuild_extensions/dsl.rb#L357), but was mislead by the argument name 'architectures' since (as the description states) it applies only to distribution checking. One could however add similar functionality like Autoproj.only_on_arch

**Comment by doudou** [comment]
Well ... my boat's main computer is still an "embedded system" for me. I guess I meant "headless", really.

Maybe we should have kind of a "standard" configuration parameter to tell all packages to disable their GUI ?

**Comment by 2maz** [comment]
I see - headless makes more sense. 
I could check the user configuration for DISABLE_GUI, NO_GUI or HEADLESS being set. Just examples, maybe you have a better suggestion or preference for the configuration parameter name.

**Comment by doudou** [comment]
All the choices you're proposing are fine for me. I would make it a silent configuration parameter (i.e. not declare it). What do you think ?

**Comment by 2maz** [comment]
I would keep it silent as well. Updated accordingly, now using DISABLE_GUI

**Pull request merged**
