### PR TITLE
gtsam package into the package set

### PR DESCRIPTION
**Pull request by jhidalgocarrio**
This PR add pkgconfig gtsam.pc for the gtsam library. It also update to the new gtsam branch.
In addition, it fixes some missing boost modules like boost-serialization

### CODE REVIEW

**Comment by 2maz** [comment]
Tested on Ubuntu 14.04: leading to the following  ../gtsam/libgtsamRelWithDebInfo.so.4.0.0: undefined reference to `boost::timer::cpu_timer::elapsed() const'
Looks like you have to add 'libboost-timer-dev' to the osdeps and dedendency list

I guess you could squash some of the commits -- but there might be other opinions (@doudou).

**Comment by jhidalgocarrio** [comment]
Thanks @2maz for testing this PR. The commits are now squashed into one single commit.

Tested on Ubuntu14.04:  I cannot reproduce the dependency error. 'libboost-timer-dev' is taken from rock.osdeps file

$ ld build/gtsam/libgtsam.so.4.0.0 
ld: warning: cannot find entry symbol _start; not setting start address

Do you have a longer text output for the linking error?

**Comment by 2maz** [comment]
Do you have an entry for 'libboost-timer-dev' somewhere in your package sets, since it is currently not part of the  rock.osdeps -> 'boost' definition?

**Comment by doudou** [comment]
I think we should stop adding even more entries to 'boost'. I would very much prefer to start pointing to separate boost libraries (i.e. add a boost-timer osdep for boost-timer, boost-serialization for boost serialization), and in fine "split" the current boost entry in its constituents.

**Comment by jhidalgocarrio** [comment]
@2maz libboost-timer-dev is included under boost in rock.osdepend. It is part in one of the commits of this PR.
@doudou I agree. However, splitting already included boost modules might break some existing rock packages. Therefore, I will leave boost as it was before this PR (system, filesystem, iostream, etc...) and create separated ones for those extra ones needed for gtsam (i.e. boost-timer, boost-serialization and boost-date-time)

**Comment by doudou** [comment]
> Therefore, I will leave boost as it was before this PR

Yes, you should definitely. Splitting it up would be the subject of another PR ... :P

**Comment by doudou** [comment]
Why did you close the PR ? You could have just amended it ... no ?

**Comment by jhidalgocarrio** [comment]
I deleted my local fork :-D . Now the PR has written " merge 15 commits into rock-core:master from unknown repository"
I guess in that case the only solution is to create a new PR?

**Comment by doudou** [comment]
Ah ... I guess so too.

**Pull request closed without merging**
