### PR TITLE
Add library control/joint_control_base

### PR DESCRIPTION
**Pull request by dmronga**
The CI in use has a time limit for building. Hence, we require a particular branch naming schema for PRs, so that a single package build can be tested.

Use the following schema to trigger the build: `update__<name-of-your-package>`
For instance to add an oroGen package `drivers/orogen/new_driver`, create the following branch to create your PR: `update__drivers/orogen/new_driver`

### CODE REVIEW

**Comment by doudou** [comment]
Let's try to pick a package name that is not *this* generic. From what I see in the package itself, the goal is to build a package with a common set of types, related to arm control ? So maybe 'joint_generation_types` ?

Also, in the package itself, the file names do not follow Rock's convention (CamelCase.hpp/CamelCase.cpp)

**Comment by dmronga** [comment]
The types actually come from the task library orogen-trajectory_generation (which is based on control-reflexxes) and we require them now in a different task library, so I would like to move them outside orogen-trajectory_generation. You are right. The name (also the name of the task library) is too generic. How about joint_control_types or joint_control_base for the library?

**Comment by doudou** [comment]
`control/joint_control_base` would be my preferred option.

**Comment by dmronga** [comment]
ok

**Comment by doudou** [comment]
@2maz since the overall agreement was to rename the package (something you have not objected to), and it has not been done, I'm puzzled by the review approval here.

**Comment by 2maz** [comment]
> @2maz since the overall agreement was to rename the package (something you have not objected to), and it has not been done, I'm puzzled by the review approval here.

sorry, obvious error - rather interprete now the approval on the basic comp basically meaning

> @2maz since the overall agreement was to rename the package (something you have not objected to), and it has not been done, I'm puzzled by the review approval here.

@doudou sorry for the confusion and thx for pointing this out, was only having the internal review in mind

**Comment by doudou** [comment]
> > @2maz since the overall agreement was to rename the package (something you have not objected to), and it has not been done, I'm puzzled by the review approval here.
> 
> @doudou sorry for the confusion and thx for pointing this out, was only having the internal review in mind

That's what reviews are for.

**Comment by dmronga** [comment]
Anything else missing or can you merge this?

**Pull request merged**
