### PR TITLE
fixed libproc for debian 8.0

### PR DESCRIPTION
**Pull request by goldhoorn**

### CODE REVIEW

**Comment by doudou** [comment]
The best format is:

```
old_debian_version,older_debian_version:
  - specific_package
default: # entry for the debian versions after old_debian_version until now
 - another_package
```

This way, one has to update the entry only when a newer debian release changed the package name. Until then, nothing has to be changed.

**Comment by goldhoorn** [comment]
The problem here is that default was used for 'old' debian versions, not 
the most recent ones, and i don't know which "old" debian versions we 
are still spporting :-(

On 16.01.2015 13:21, Sylvain Joyeux wrote:
>
> The best format is:
>
> |old_debian_version,older_debian_version:
>    - specific_package
> default: # entry for the debian versions after old_debian_version until now
>   - another_package
> |
>
> This way, one has to update the entry only when a newer debian release 
> changed the package name. Until then, nothing has to be changed.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/rock-package_set/pull/32#issuecomment-70246505>.
>


-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by doudou** [comment]
We don't officially support debian in the first place. I am personally fine supporting only current-stable.

**Comment by goldhoorn** [comment]
*updated*

**Comment by doudou** [comment]
and merged

**Pull request merged**
