### PR TITLE
getting mtk from the forked repository in the github rock-slam

### PR DESCRIPTION
**Pull request by jhidalgocarrio**

### CODE REVIEW

**Comment by goldhoorn** [comment]
Could'n you get your patches in mtk-mainline?

**Comment by jhidalgocarrio** [comment]
@goldhoorn do you mean this #52?

**Comment by goldhoorn** [comment]
ah ok don't know this...

side remark: you can contakt udo frese directly. maybe he can post on openslam a note that the development is continued on github if you don't get feedback

**Comment by goldhoorn** [comment]
@jhidalgocarrio: i spoke with udo, please contact http://www2.informatik.uni-freiburg.de/~stachnis/ maybe they are open to move their development to github too. But for now i merge, but please wrote a email to them

**Pull request merged**
