### PR TITLE
Update aruco v2

### PR DESCRIPTION
**Pull request by Rauldg**
This should be equivalent to doing a rebase of the aruco_v2 branch on top of master.

A rebase would make the history look cleaner than merging this though.

@2maz

### CODE REVIEW

**Comment by doudou** [comment]
Hey ... this PR is not going to the master branch. Any reason ?

**Comment by Rauldg** [comment]
This is just a rebase, to keep up to date with the master branch changes. Maybe not anymore up to date. It is actually quite annoying to have to rebase it periodically.

It would be great to have these changes in the master branch. I guess that the reason why this has not been pursued before is that the Aruco V2 branch points to code which is not provided directly by the developers of the library. 

I asked the Aruco developers what they think about putting their code on Github or some other host for repositories, but they seem to be busy with other things.

**Comment by doudou** [comment]
> the Aruco V2 branch points to code which is not provided directly by the developers of the library

... where is the code that is provided by the developers of the library, then ? They do provide something somewhere ? I don't get it...

**Comment by Rauldg** [comment]
[They](https://www.uco.es/investiga/grupos/ava/node/26) provide their software through Sourceforge [here](https://sourceforge.net/projects/aruco/files/). In Sourceforge the latest (3.x) and the 1.x versions can be found, but not the 2.x which is the one used by this branch.

**Comment by 2maz** [comment]
With notice to rock-users we could move forward to the most recent version 3 which is officially available.

@Rauldg: the internally used orogen component was working with v2 but is now compatible with v3

**Comment by Rauldg** [comment]
>@Rauldg: the internally used orogen component was working with v2 but is now compatible with v3

In that case we can drop this PR.

**Pull request closed without merging**
