### PR TITLE
The gem for net-ssh has to be of version <=2.10

### PR DESCRIPTION
**Pull request by Rauldg**
Related to this discussion:
https://github.com/rock-core/rock-package_set/issues/83

### CODE REVIEW

**Comment by goldhoorn** [comment]
@doudou i'm not sure if this file is picked automatically?. If so :+1: for merge

**Comment by doudou** [comment]
@rauldg: why are you working on the rock-rc branch ?

**Comment by goldhoorn** [comment]
@Rauldg : can you please create a new PR against master and close this?

**Comment by Rauldg** [comment]
Done!

In our project we were using rock-rc for that package.

**Comment by goldhoorn** [comment]
On 07.10.2015 10:43, Raúl Domínguez wrote:
>
> Done!
>
> In our project we were using rock-rc for that package.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/rock-package_set/pull/85#issuecomment-146119743>.
>
rock-rc get's deleted soon (it should already have, however) you should 
NOT use the rc-branch at all.
Use the tag for your relese instead.

P.S. did you tested if this is workign for you?

-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by Rauldg** [comment]
My guess is that in the project we had the rc branch before the release was done and then we didn't change the branch.

**Comment by goldhoorn** [comment]
On 07.10.2015 11:25, Raúl Domínguez wrote:
>
> My guess is that in the project we had the rc branch before the 
> release was done and then we didn't change the branch.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/rock-package_set/pull/85#issuecomment-146130111>.
>
Statement is still valid: the rc-branch will be deleted soon!, never 
ever use the rc-branch for production



-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by Rauldg** [comment]
Yes, you are right, we were bad. 

On the other hand, there is no stable branch on this package (as for others), the policy is then to send bug-fixes to the master branch?

**Comment by goldhoorn** [comment]
On 07.10.2015 11:55, Raúl Domínguez wrote:
>
> Yes, you are right, we were bad.
>
> On the other hand, there is no stable branch on this package (as for 
> others), the policy is then to send bug-fixes to the master branch?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/rock-package_set/pull/85#issuecomment-146136152>.
>
The package sets does not have a master branch because they itself 
separate when they are used in a stable setup, therefore as you 
suggested you have to send PRs against master.

One remark against the PR, the os-dep should only be valid for stable, 
but i don't know howto archive this: (question to @doudou)

-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by Rauldg** [comment]
On 07.10.2015 12:02, Matthias Goldhoorn wrote:
> On 07.10.2015 11:55, Raúl Domínguez wrote:
> >
> > Yes, you are right, we were bad.
> >
> > On the other hand, there is no stable branch on this package (as for
> > others), the policy is then to send bug-fixes to the master branch?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/rock-core/rock-package_set/pull/85#issuecomment-146136152>.
> >
> The package sets does not have a master branch because they itself
> separate when they are used in a stable setup, therefore as you
> suggested you have to send PRs against master.
What do you mean with "they itself separate when used in a stable 
setup"? I understand that a "stable setup" is a rock installation for 
which stable flavour was selected. What do you mean with "they itself 
separate"?
>
> One remark against the PR, the os-dep should only be valid for stable,
> but i don't know howto archive this: (question to @doudou)
The PR should only affect users using ruby1.9 so for the next stable we 
don't need it that is right, but for the current stable we do.
>
> -- 
> Dipl.-Inf. Matthias Goldhoorn
> Space and Underwater Robotic
>
> Universität Bremen
> FB 3 - Mathematik und Informatik
> AG Robotik
> Robert-Hooke-Straße 1
> 28359 Bremen, Germany
>
> Zentrale: +49 421 178 45-6611
>
> Besuchsadresse der Nebengeschäftstelle:
> Robert-Hooke-Straße 5
> 28359 Bremen, Germany
>
> Tel.: +49 421 178 45-4193
> Empfang: +49 421 178 45-6600
> Fax: +49 421 178 45-4150
> E-Mail: matthias.goldhoorn@informatik.uni-bremen.de
>
> Weitere Informationen: http://www.informatik.uni-bremen.de/robotik
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/rock-package_set/pull/85#issuecomment-146138009>.
>

-- 
  Raúl Domínguez (M.Sc.)
  Space Robotics

  Besuchsadresse der Nebengeschäftsstelle:
  DFKI GmbH
  Robotics Innovation Center
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Postadresse der Hauptgeschäftsstelle Standort Bremen:
  DFKI GmbH
  Robotics Innovation Center
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Tel.:     +49 421 178 45-6617
  Zentrale: +49 421 178 45-0
  Fax:      +49 421 178 45-4150 (Faxe bitte namentlich kennzeichnen)
  E-Mail:   raul.dominguez@dfki.de
  
  Weitere Informationen: http://www.dfki.de/robotik
  -----------------------------------------------------------------------
  Deutsches Forschungszentrum fuer Kuenstliche Intelligenz GmbH
  Firmensitz: Trippstadter Straße 122, D-67663 Kaiserslautern
  Geschaeftsfuehrung: Prof. Dr. Dr. h.c. mult. Wolfgang Wahlster
  (Vorsitzender) Dr. Walter Olthoff
  Vorsitzender des Aufsichtsrats: Prof. Dr. h.c. Hans A. Aukes
  Amtsgericht Kaiserslautern, HRB 2313
  Sitz der Gesellschaft: Kaiserslautern (HRB 2313)
  USt-Id.Nr.:    DE 148646973
  Steuernummer:  19/673/0060/3

**Comment by goldhoorn** [comment]
You are right in master we dont have ruby1.9 ;) 

Am 7. Oktober 2015 13:22:58 MESZ, schrieb "Raúl Domínguez" <notifications@github.com>:
>
>On 07.10.2015 12:02, Matthias Goldhoorn wrote:
>> On 07.10.2015 11:55, Raúl Domínguez wrote:
>> >
>> > Yes, you are right, we were bad.
>> >
>> > On the other hand, there is no stable branch on this package (as
>for
>> > others), the policy is then to send bug-fixes to the master branch?
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > 
>>
><https://github.com/rock-core/rock-package_set/pull/85#issuecomment-146136152>.
>> >
>> The package sets does not have a master branch because they itself
>> separate when they are used in a stable setup, therefore as you
>> suggested you have to send PRs against master.
>What do you mean with "they itself separate when used in a stable 
>setup"? I understand that a "stable setup" is a rock installation for 
>which stable flavour was selected. What do you mean with "they itself 
>separate"?
>>
>> One remark against the PR, the os-dep should only be valid for
>stable,
>> but i don't know howto archive this: (question to @doudou)
>The PR should only affect users using ruby1.9 so for the next stable we
>
>don't need it that is right, but for the current stable we do.
>>
>> -- 
>> Dipl.-Inf. Matthias Goldhoorn
>> Space and Underwater Robotic
>>
>> Universität Bremen
>> FB 3 - Mathematik und Informatik
>> AG Robotik
>> Robert-Hooke-Straße 1
>> 28359 Bremen, Germany
>>
>> Zentrale: +49 421 178 45-6611
>>
>> Besuchsadresse der Nebengeschäftstelle:
>> Robert-Hooke-Straße 5
>> 28359 Bremen, Germany
>>
>> Tel.: +49 421 178 45-4193
>> Empfang: +49 421 178 45-6600
>> Fax: +49 421 178 45-4150
>> E-Mail: matthias.goldhoorn@informatik.uni-bremen.de
>>
>> Weitere Informationen: http://www.informatik.uni-bremen.de/robotik
>>
>> —
>> Reply to this email directly or view it on GitHub 
>>
><https://github.com/rock-core/rock-package_set/pull/85#issuecomment-146138009>.
>>
>
>-- 
>  Raúl Domínguez (M.Sc.)
>  Space Robotics
>
>  Besuchsadresse der Nebengeschäftsstelle:
>  DFKI GmbH
>  Robotics Innovation Center
>  Robert-Hooke-Straße 5
>  28359 Bremen, Germany
>  
>  Postadresse der Hauptgeschäftsstelle Standort Bremen:
>  DFKI GmbH
>  Robotics Innovation Center
>  Robert-Hooke-Straße 1
>  28359 Bremen, Germany
>  
>  Tel.:     +49 421 178 45-6617
>  Zentrale: +49 421 178 45-0
>  Fax:      +49 421 178 45-4150 (Faxe bitte namentlich kennzeichnen)
>  E-Mail:   raul.dominguez@dfki.de
>  
>  Weitere Informationen: http://www.dfki.de/robotik
>-----------------------------------------------------------------------
>  Deutsches Forschungszentrum fuer Kuenstliche Intelligenz GmbH
>  Firmensitz: Trippstadter Straße 122, D-67663 Kaiserslautern
>  Geschaeftsfuehrung: Prof. Dr. Dr. h.c. mult. Wolfgang Wahlster
>  (Vorsitzender) Dr. Walter Olthoff
>  Vorsitzender des Aufsichtsrats: Prof. Dr. h.c. Hans A. Aukes
>  Amtsgericht Kaiserslautern, HRB 2313
>  Sitz der Gesellschaft: Kaiserslautern (HRB 2313)
>  USt-Id.Nr.:    DE 148646973
>  Steuernummer:  19/673/0060/3
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/rock-core/rock-package_set/pull/85#issuecomment-146159917

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Pull request closed without merging**
