### PR TITLE
Update  drivers/orogen/controldev_websocket

### PR DESCRIPTION
**Pull request by henriquejsfj**

### CODE REVIEW

**Comment by henriquejsfj** [comment]
@doudou

**Comment by henriquejsfj** [comment]
ping @doudou

**Comment by doudou** [comment]
Could you create a pull request on our internal package set (wetpaint), which adds the package to the x86-control metapackage ? Make sure it depends on this PR.

This should be enough to have it tested in CI. I'd really like to have it there before merging, since it pulls new dependencies, including one other new package.

**Comment by doudou** [comment]
Ping @henriquejsfj

**Pull request merged**
