### PR TITLE
Updated KDL location and patches

### PR DESCRIPTION
**Pull request by goldhoorn**

### CODE REVIEW

**Comment by goldhoorn** [comment]
@dettmann, could you check this?

**Comment by dettmann** [comment]
it worked for me

**Comment by annaborn** [comment]
+1

**Comment by planthaber** [comment]
This patch is not compatible with the next and stable versions of kdl:
, there kdl is pinned to commit
      commit: 8e50979fdfb5e7a0ad1751162f39b3b32452efbc
in the source.stable.yml

**Pull request merged**
