### PR TITLE
add control/ruby_sdformat

### PR DESCRIPTION
**Pull request by doudou**
NOTE: this is do-not-merge as I'll need to create the git repository in rock-control first.

Code is here for now:
  https://github.com/Brazilian-Institute-of-Robotics/tools-ruby_sdf

### CODE REVIEW

**Comment by goldhoorn** [comment]
When do you will create the repro?

**Comment by doudou** [comment]
When I get an all-clear from someone that it is OK

**Comment by doudou** [comment]
I interpreted your question as an OK ... It is moved now https://github.com/rock-control/control-ruby_sdformat

**Comment by 2maz** [comment]
I guess the do-not-merge label can be removed here, since the package exists now. Ok for merge as I see it.

**Comment by goldhoorn** [comment]
:+1:

**Comment by goldhoorn** [comment]
I had to modify this. You added your package in the stable section but you repro has no stable branch. I modified the package set directly) and modes it to the top of the file. Either you create the stable branch and create a new pr or mention this package should become stable during the next release period.

**Pull request merged**
