### PR TITLE
update mtk patch for dynamic size measurement vectors

### PR DESCRIPTION
**Pull request by jhidalgocarrio**
This patch allows dynamic measurement vector size for UKF on manifolds

### CODE REVIEW

**Comment by doudou** [comment]
If you start to really add functionality to mtk, it would be a good idea to get your contribution included upstream and/or having your own repository, no ?

**Comment by jhidalgocarrio** [comment]
You are completely right but so far it is the only change needed. In case there will be more in the future I will "fork" from the existing package in openslam.org and store it in github (e.g.: rock-slam)

**Comment by doudou** [comment]
> You are completely right but so far it is the only change needed. In case there will be more in the future I will "fork" from the existing package in openslam.org and store it in github (e.g.: rock-slam)

That's not what I meant ... Is MTK still developed ? Have you contacted the developers.

The line you're "crossing" here is that these are not just modifications needed to get the package to build on Rock. You're adding modifications to the package...

**Comment by jhidalgocarrio** [comment]
MTK is still under development. I contacted the developers a while ago. The repo is not public and so far it seems to be like this.
I guess I'm "breaking" the rule for patches since it is not to just make it compiling under rock.
The code is under BSD. I could make a repo in github. Do you suggest to do that instead of merging the pull-request? I am fine with it.

**Comment by jhidalgocarrio** [comment]
Close this PR without merging. I am going to fork a MTK from the public package in openslam.org

**Comment by doudou** [comment]
> The code is under BSD. I could make a repo in github. Do you suggest to do that instead of merging the pull-request? I am fine with it.

Yes. You are in effect forking mtk (because you add new functionality), so that would be IMO a better choice.

**Pull request closed without merging**
