### PR TITLE
add libvlc plugins for ubuntu

### PR DESCRIPTION
**Pull request by planthaber**
Instanciating libvlc without plugins installed does not work (returns nullptr), so plugins are needed to use libvlc at all

### CODE REVIEW

**Comment by 2maz** [comment]
Looks like this package is only available for bionic and onwards: https://packages.ubuntu.com/bionic/vlc-plugin-base

**Comment by planthaber** [comment]
Isn't rock also supporting only bionic and onwards?

**Comment by 2maz** [comment]
> Isn't rock also supporting only bionic and onwards?

Just mentioning it since it might be in your own interest, given that we also still have an active 16.04 in our internal CI pipeline.

**Review by 2maz — APPROVED** [review]

**Comment by hemker** [comment]
@planthaber @2maz Just saw this PR still open, can it be closed?

**Pull request merged**
