### PR TITLE
snap: remove -lrt from cflags, result in a lot less compiler warnings

### PR DESCRIPTION
**Pull request by goldhoorn**

### CODE REVIEW

**Comment by 2maz** [comment]
This is a rather weak argumentation to remove the flag ;) What are the warnings?
As from what I see snap requires it for UNIX due to glib-adv/sock-new.cpp.

**Comment by goldhoorn** [comment]
On 15.10.2015 15:10, Thomas Roehr wrote:
>
> This is a rather weak argumentation to remove the flag ;) What are the
> warnings?
> As from what I see snap requires it for UNIX due to glib-adv/sock-new.cpp.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rock-core/rock-package_set/pull/90#issuecomment-148379697>.
>
It requires the library, but the given statement adds -lrt to the cflags
and not to the LD_flags

-- 
 Dipl.-Inf. Matthias Goldhoorn 
 Space and Underwater Robotic

 Universität Bremen
 FB 3 - Mathematik und Informatik
 AG Robotik
 Robert-Hooke-Straße 1
 28359 Bremen, Germany
 
 Zentrale: +49 421 178 45-6611
 
 Besuchsadresse der Nebengeschäftstelle: 
 Robert-Hooke-Straße 5
 28359 Bremen, Germany
 
 Tel.:    +49 421 178 45-4193
 Empfang: +49 421 178 45-6600
 Fax:     +49 421 178 45-4150
 E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

 Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by 2maz** [comment]
Ok, to merge but pls reword the commit. 
To clarify: snap.pc.in file is already forwarding -lrt, but CMakeLists.txt wrongly adds linker statement to cflags.

**Comment by goldhoorn** [comment]
*updated*

**Comment by 2maz** [comment]
merged

**Pull request merged**
