### PR TITLE
include control/sdformat package

### PR DESCRIPTION
**Pull request by gustavoneves12**
include control/sdformat to libs.autobuild
include control/format to source.yaml

### CODE REVIEW

**Comment by doudou** [comment]
I could merge it ... but that would seem a little bit too self-serving. URDF and sim people, I'd like some opinion
/cc @maltewi, @goldhoorn

**Comment by goldhoorn** [comment]
i'm not working on sim/urdf (activly), maybe @kavonszadkowski has a opinion here?

**Comment by kavonszadkowski** [comment]
I'm lacking a bit of context, so not sure what kind of opinion is expected ;)
@jmachowinski recently implemented loading URDF joint information in Rock to avoid having to define all transforms yet again in Ruby. This implementation uses our [SMURF parser](https://github.com/rock-simulation/smurf_parser) and thus allows to write any additional transforms to SMURF. That last feature is something I hope to add to [Phobos](https://github.com/rock-simulation/phobos) in the coming days.

I don't see how that should collide with loading data from SDF, unless being able to read multiple input formats is somehow a bad thing.

**Comment by doudou** [comment]
> I don't see how that should collide with loading data from SDF, unless being able to read multiple input formats is somehow a bad thing.

Not a bad thing IMO ... Given where we're getting with SDF, I think that we'll end up having support for all formats in the end.

I was more wondering about the package name. To parallel with URDF, we chose to put sdformat in control/. Since that seems to not shock anyone, I'm merging.

**Pull request merged**
