### PR TITLE
add ceres solver as os dependency

### PR DESCRIPTION
**Pull request by D-Alex**
ceres is now available as os package

### CODE REVIEW

**Comment by goldhoorn** [comment]
I see ceres only availible on debian experimantal, neitehr on ubuntu, and neither on any stable os we support:

http://packages.ubuntu.com/search?keywords=ceres&searchon=names&suite=all&section=all
https://packages.debian.org/search?keywords=ceres&searchon=names&suite=all&section=all

**Comment by D-Alex** [comment]
You are right. I am on ubuntu 14.04 and the package is coming from 
/var/lib/apt/lists/packages.ros.org_ros_ubuntu_dists_trusty_main_binary-amd64_Packages 

The question is now. How do we handle this?

**Comment by goldhoorn** [comment]
We don't,
rock officially supports from the osdeps only deps that are provided by
the system, not by ppa's oder user additions.

Sorry,
you have to add it as regular package.



On 16.11.2015 11:23, Alexander Duda wrote:
>
> You are right. I am on ubuntu 14.04 and the package is coming from
> /var/lib/apt/lists/packages.ros.org_ros_ubuntu_dists_trusty_main_binary-amd64_Packages
>
>
> The question is now. How do we handle this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rock-core/rock-package_set/pull/93#issuecomment-156980615>.
>


-- 
 Dipl.-Inf. Matthias Goldhoorn 
 Space and Underwater Robotic

 Universität Bremen
 FB 3 - Mathematik und Informatik
 AG Robotik
 Robert-Hooke-Straße 1
 28359 Bremen, Germany
 
 Zentrale: +49 421 178 45-6611
 
 Besuchsadresse der Nebengeschäftstelle: 
 Robert-Hooke-Straße 5
 28359 Bremen, Germany
 
 Tel.:    +49 421 178 45-4193
 Empfang: +49 421 178 45-6600
 Fax:     +49 421 178 45-4150
 E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

 Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by goldhoorn** [comment]
Why adding this to the rock package set it does not exist any task or script that uses it.

**Comment by goldhoorn** [comment]
Reopen a updated one if you want to have it in master and the open package-set, as long i close this

**Pull request closed without merging**
