### PR TITLE
Fixed default for qglviewer.

### PR DESCRIPTION
**Pull request by skasperski**

### CODE REVIEW

**Comment by doudou** [comment]
This directly goes against the change that had been made just before by @planthaber ... you'll have to decide what's the right thing to do here (https://github.com/skasperski/rock-package_set/commit/0a5956dbd6efb681ff41e67bfa5342de15e5d60a).

Generally speaking, whenever you feel that you're "fixing" something, explain what you're fixing in the commit message / PR message. It would help understanding what's going on.

**Comment by skasperski** [comment]
I think qt4 is only required on older distributions. On xenial qt5 is used with rock, which causes a clash with this dependency.

**Comment by planthaber** [comment]
I think I picked qt4 not to break anything, as before qt4 was the OS default.
Also, as the ruby bindings are only available for qt4, i thought using qglviewer-qt4 has less potential to crash when used to visualize with vizkit.

**Comment by skasperski** [comment]
After talking to Steffen it seems like qt4 is really the better solution for rock. The original issue was probably a problem with the rock-master_16.09 binary distribution.

**Pull request closed without merging**
