### PR TITLE
Added tools/class_loader

### PR DESCRIPTION
**Pull request by goldhoorn**

### CODE REVIEW

**Comment by doudou** [comment]
If the goal (as discussed on the ML) is to make in fine class_loader Rock's plugin loader, this should definitely go in rock.core

**Comment by goldhoorn** [comment]
So far i would like to use it in mars and 'replace/extend' the loading 
mechanism there.

It seems that the class_loader get started to use for loading.
The final discussion for envire/vizkit is not finished but the class 
loader seems to win. So i starte to add it to rock.



On 29.01.2015 19:54, Sylvain Joyeux wrote:
>
> If the goal (as discussed on the ML) is to make in fine class_loader 
> Rock's plugin loader, this should definitely go in rock.core
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/rock-package_set/pull/36#issuecomment-72081804>.
>


-- 
  --
  Matthias Goldhoorn
  Unterwasserrobotik
  
  Standort Bremen:
  DFKI GmbH
  Robotics Innovation Center
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Phone: +49 (0)421 218-64100
  Fax:   +49 (0)421 218-64150
  E-Mail: robotik@dfki.de
  
  Weitere Informationen: http://www.dfki.de/robotik
  -----------------------------------------------------------------------
  Deutsches Forschungszentrum fuer Kuenstliche Intelligenz GmbH
  Firmensitz: Trippstadter Straße 122, D-67663 Kaiserslautern
  Geschaeftsfuehrung: Prof. Dr. Dr. h.c. mult. Wolfgang Wahlster
  (Vorsitzender) Dr. Walter Olthoff
  Vorsitzender des Aufsichtsrats: Prof. Dr. h.c. Hans A. Aukes
  Amtsgericht Kaiserslautern, HRB 2313
  Sitz der Gesellschaft: Kaiserslautern (HRB 2313)
  USt-Id.Nr.:    DE 148646973
  Steuernummer:  19/673/0060/3
  -----------------------------------------------------------------------

**Comment by doudou** [comment]
> The final discussion for envire/vizkit is not finished but the class loader seems to win. So i starte to add it to rock.

Unless there is a huge urgency, just ask on the ML. I would really prefer putting it to rock.core directly

**Comment by goldhoorn** [comment]
Moved to https://github.com/rock-core/package_set/pull/24

**Pull request closed without merging**
