### PR TITLE
add new dependency of control/urdfdom

### PR DESCRIPTION
**Pull request by planthaber**

### CODE REVIEW

**Comment by moooeeeep** [comment]
Thanks! I was just about to create a PR myself.

There are manifests for the related packages that might need to be adjusted too:

* https://github.com/rock-core/rock-package_set/blob/master/manifests/control/urdfdom.xml
* https://github.com/rock-core/rock-package_set/blob/master/manifests/control/urdfdom_headers.xml

**Comment by moooeeeep** [comment]
urdfdom_headers probably doesn't need the dependency at all. Apparantly the dep to boost can also be dropped.

**Comment by planthaber** [comment]
Added changes: Actually removed dependencies from the autobuild file and updated those in the manifest xml files

**Comment by moooeeeep** [comment]
Looks good to me.

Related info: The urdfdom library has upgraded their dep to tinyxml to now tinyxml2 (related announcement: https://discourse.ros.org/t/upcoming-api-break-in-urdfdom/34750). Because some API functions involve tinyxml types, this may break client code that involves these API (example: https://github.com/ARC-OPT/wbc/blob/b51ee0c1bf09c19c6cf6109f78da44105aca9c07/src/tools/URDFTools.cpp#L126).

Not sure if it our responsibility to maintain API stability of all provided packages here forever? If so, we could simply pin the version of the package `control/urdfdom` to the [last working release](https://github.com/ros/urdfdom/releases/tag/3.0.0), or the [last working commit](6d3c5de088359523857befbe730dbdd5543e35ba)...

**Comment by planthaber** [comment]
Pinning should be done in the overrides of the buildconf where required, not in a package_set. (at least as much as possible).

**Pull request merged**
