### PR TITLE
Install gstreamer0.10 on Ubuntu 16.04

### PR DESCRIPTION
**Pull request by jmachowinski**
Fixed compilation issues with camera_usb package

### CODE REVIEW

**Comment by doudou** [comment]
> Fixed compilation issues with camera_usb package

Shouldn't camera_usb be updated instead ?

**Comment by jmachowinski** [comment]
Update to gstreamer1.0 is not trivial.

**Comment by doudou** [comment]
If you're not willing to update, I would rather that you create a new `gstreamer0.10` entry that pins to 0.10 and make camera_usb depend on it.

**Comment by 2maz** [comment]
closing as outdated - anyhow, the reference branch is not related to the topic of this PR anymore

**Pull request closed without merging**
